export enum SystemRole {
    SUPERADMIN = 'SUPERADMIN',
    ADMIN = 'ADMIN',
    REGIONAL_ADMIN = 'REGIONAL_ADMIN',
    MODERATOR = 'MODERATOR',
    CONTENT_ADMIN = 'CONTENT_ADMIN',
    SALES = 'SALES',
    VOLUNTEER_ADMIN = 'VOLUNTEER_ADMIN',
    COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
}

export enum CommunityTier {
    FREE = 'FREE',
    UBUNTU = 'UBUNTU',
    IMANI = 'IMANI',
    KIONGOZI = 'KIONGOZI',
}

export enum AccountFlags {
    VOLUNTEER = 'VOLUNTEER',
    VOLUNTEER_MANAGER = 'VOLUNTEER_MANAGER',
    CITY_SCOPE = 'CITY_SCOPE',
    ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
    PROFILE_COMPLETED = 'PROFILE_COMPLETED',
    MEMBER_ID_NOTIFIED = 'MEMBER_ID_NOTIFIED',
    SHADOW_BANNED = 'SHADOW_BANNED',
    
    // Platform Extra Access Flags
    CAN_ACCESS_ORG_MANAGEMENT = 'CAN_ACCESS_ORG_MANAGEMENT',
    CAN_ACCESS_REGIONAL_CHAPTERS = 'CAN_ACCESS_REGIONAL_CHAPTERS',
    CAN_ACCESS_FORUM_MODERATION = 'CAN_ACCESS_FORUM_MODERATION',
    CAN_ACCESS_VOLUNTEER_CENTER = 'CAN_ACCESS_VOLUNTEER_CENTER',
    CAN_ACCESS_EVENTS = 'CAN_ACCESS_EVENTS',
    CAN_ACCESS_PARTNERSHIPS = 'CAN_ACCESS_PARTNERSHIPS',
    CAN_ACCESS_MEMBERSHIP_CENTER = 'CAN_ACCESS_MEMBERSHIP_CENTER',
    CAN_ACCESS_CONTENT_RESOURCES = 'CAN_ACCESS_CONTENT_RESOURCES',
    CAN_ACCESS_SALES_INVENTORY = 'CAN_ACCESS_SALES_INVENTORY',
    CAN_ACCESS_ANALYTICS = 'CAN_ACCESS_ANALYTICS',
    CAN_ACCESS_PLATFORM_SETTINGS = 'CAN_ACCESS_PLATFORM_SETTINGS',
    CAN_ACCESS_REVENUE_CENTER = 'CAN_ACCESS_REVENUE_CENTER',
}


export enum ConnectionPreference {
    OPEN = 'OPEN',
    CHAPTER_ONLY = 'CHAPTER_ONLY',
    NO_CONNECTIONS = 'NO_CONNECTIONS',
}
