export enum SystemRole {
    SUPERADMIN = 'SUPERADMIN',
    ADMIN = 'ADMIN',
    REGIONAL_ADMIN = 'REGIONAL_ADMIN',
    MODERATOR = 'MODERATOR',
    CONTENT_ADMIN = 'CONTENT_ADMIN',
    SALES = 'SALES',
    VOLUNTEER_ADMIN = 'VOLUNTEER_ADMIN',
    COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
}

export enum CommunityTier {
    FREE = 'FREE',
    UBUNTU = 'UBUNTU',
    IMANI = 'IMANI',
    KIONGOZI = 'KIONGOZI',
}

export enum AccountFlags {
    VOLUNTEER = 'VOLUNTEER',
    VOLUNTEER_MANAGER = 'VOLUNTEER_MANAGER',
    CITY_SCOPE = 'CITY_SCOPE',
    ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
    PROFILE_COMPLETED = 'PROFILE_COMPLETED',
    MEMBER_ID_NOTIFIED = 'MEMBER_ID_NOTIFIED',
    SHADOW_BANNED = 'SHADOW_BANNED',
}


export enum ConnectionPreference {
    OPEN = 'OPEN',
    CHAPTER_ONLY = 'CHAPTER_ONLY',
    NO_CONNECTIONS = 'NO_CONNECTIONS',
}
